### ISSUE TITLE
Add a option to hide icon from App Drawer

### ISSUE THREAD

**Issue by Vipin2003** [OxrxL/mMicroG#1]
Please add a option or make it integrated within the app in further builds (like vanced one) to hide the app icon from Launcher or App drawer. It is good for those who have stock UI and no hiding options for Apps.

**Comment by OxrxL** [comment]
This is a 1:1 (as far as possible) of MicroG, to simplify upgradability (and also, although unrelated to your request, minimize errors that ReVanced apps can show).

For all that similar implementations ask @inotia00
